### ISSUE TITLE
Avoid/Disable One-off dynos autorestart

### ISSUE THREAD

**Issue by Porkechebure** [heroku/platform-api#119]
I have a docker ubuntu container with a python script inside which dies under certain conditions.
I have deployed it as a one-off dyno.
I have scheduled it with heroku scheduler to run twice a day.
I tried every possible way to stop a python script:
Normal ways, sys.exit, quit(), whatever.
No matter how gracefully I terminate it, heroku says "State changed from up to crashed" and try to restart the dyno continuosly.
From what I read this is wanted, and it will try to run the dyno continuosly, for a certain amount of times, then it gives it a cooldown and retries. The cooldown gradually increases.

Now this is ridiculous. One-off are supposed to serve one-shot scripts that do a certain job, then shut off when finished.

How I avoid this continuous unwanted restart?

**Comment by edmorley** [comment]
Hi! This repo is not for generic Heroku issues, but the Ruby gem for interacting with the Heroku API. For support issues please see https://help.heroku.com

**Comment by Porkechebure** [comment]
YEAHHOOOOOOOOOOOOOOOOOOOOOOOOOOOO YEAHHHHHHHH

**Comment by Porkechebure** [comment]
> Hi! This repo is not for generic Heroku issues, but the Ruby gem for interacting with the Heroku API. For support issues please see https://help.heroku.com

YAHOOOOOOOOOO
