### ISSUE TITLE
pg:wait, pg:info, or --fork using API

### ISSUE THREAD

**Issue by quarterdome** [heroku/platform-api#14]
I am able to create a new Heroku Postgres addon using the Platform API. However, it is not clear how to provision a fork of an existing database and wait until the fork is complete. 

I tried the following two options to provision the fork:

```
hk.addon.create('apartmentlist-production', { 'plan' => 'heroku-postgresql:standard-tengu', 'fork' => 'heroku-postgresql-black' } )
hk.addon.create('apartmentlist-production', { 'plan' => 'heroku-postgresql:standard-tengu', 'fork' => 'HEROKU_POSTGRESQL_BLACK_URL' } )
```

Both of the above provision an addon, but do not fork an existing DB. 

Also, when I use the `addon.info` endpoint, I do not get any of the info that `heroku pg:info` command gives me. In particular I see no way to know if a newly provisioned DB  has caught up and is ready for queries.

If Platform API is not the right tool for it, is there any other Heroku API that can help me accomplish forking a database and waiting until it is ready?

**Comment by gregnavis** [comment]
I'd also love to see PostgreSQL-specific API calls in `platform-api`. I have look at the docs and it seems they aren't there yet (but please correct me if I'm wrong). Is this something that you plan to do in the near future?

**Comment by geemus** [comment]
We've certainly heard this ask, but we don't have a timeline we can share on providing this.

**Comment by geemus** [comment]
closing in favor of #47 (just to reduce duplication a bit)

**Comment by jlerpscher** [comment]
@uhoh-itsmaciek Unfortunately, this command does not work:

```
Excon::Error::UnprocessableEntity: Expected([200, 201, 202, 204, 206, 304]) <=> Actual(422 Unprocessable Entity)
```

I can't find any way to copy a database from another app (like heroku fork command) or just migrate + seed my new database.

**Comment by uhoh-itsmaciek** [comment]
@jlerpscher Right, hobby plans do not support forking. You may be able to reverse-engineer `pg:copy` to do what you want, but this is not a supported feature of the platform right now.
