### ISSUE TITLE
Pagination does not work with caching

### ISSUE THREAD

**Issue by afn** [heroku/platform-api#16]
I'm using platform-api 0.2.0, heroics 0.0.12.

The client is caching the first page of responses only.  So the first API call returns a full set of results, whereas subsequent calls return only partial results.  Turning off caching fixes the issue.

```
2.1.1 :001 > require 'platform-api'
 => true
2.1.1 :002 > heroku = PlatformAPI.connect_oauth(token)
 => #<PlatformAPI::Client:0x00000103984780 @client=#<Heroics::Client url="https://api.heroku.com">>
2.1.1 :003 > heroku.release.list(app_name).count
 => 841
2.1.1 :004 > heroku.release.list(app_name).count
 => 200
```

**Comment by afn** [comment]
Still happening with platform-api 0.3.0 and heroics 0.0.14.

**Comment by mikehale** [comment]
I think this is actually an issue with heroics https://github.com/interagent/heroics/issues/69

**Comment by geemus** [comment]
I believe the heroics issue has been fixed (and we've had a release).
