### ISSUE TITLE
Consider renaming the gem

### ISSUE THREAD

**Issue by bgentry** [heroku/platform-api#19]
This gem has a very generic name (`platform-api`). The `require 'platform-api'` bit is weird, and it's not clear what platform you're talking about. That's especially true when using it from ruby code as `PlatformAPI`.

At the very least it would be a good idea to nest that to `Heroku::PlatformAPI` and then you could require `heroku-platform-api` or something like that.

**Comment by george** [comment]
+1

**Comment by marcusmalmberg** [comment]
+1

**Comment by mmitchellg5** [comment]
+1

**Comment by kenliu** [comment]
+1

**Comment by ykmr1224** [comment]
+1

**Comment by caifara** [comment]
+1

**Comment by backus** [comment]
+1

**Comment by rafaelcgo** [comment]
:+1:

**Comment by grosser** [comment]
@geemus pretty please ? :)

**Comment by geemus** [comment]
Noted. It seems like it might leave a pretty weird upgrade path. I also have some desire to deprecate this and create a new thing that is generated at build time instead of run time, but obviously that is a much larger undertaking.

**Comment by grosser** [comment]
how about releasing a new (heroku-platform_api) gem and releasing a 'this
is deprecated' version of the old gem (warns but works as before) ?

**Comment by geemus** [comment]
I at least largely agree that the name is not great, but it's really hard to prioritize. The current version works and lots of other things to occupy my attention. I may revisit, but just going to close this for now.

**Comment by grosser** [comment]
Do you want a PR to change it around ?
... then you'd simply release a new version and not update the old ...

**Comment by geemus** [comment]
My concern is that it would break other expectations though (as those who, for instance, have a non version-locked specified in Gemfile would no longer receive updates). I guess we could just release both, forever, but that seems not awesome also.

**Comment by grosser** [comment]
The release 1 last version that has no code and depends on the other.

**Comment by geemus** [comment]
@grosser hmm. I hadn't thought about that. That does seem like it would handle that case, if I'm not missing something. It does mean a little weirdness in sequencing (release the new thing so it will exist, then the old thing so it can rely on something that already exists?), but not intractable weirdness. Does that reflect what you had in mind?

**Comment by grosser** [comment]
yes!
want a PR for the name change/nesting ?

**Comment by geemus** [comment]
Looking back through this, I guess I do have one other point of discussion. Should we also talk about changing the namespacing from `PlatformAPI`? That seems like it might be much more problematic than just renaming the gem (though we could similarly change and leave an alias around, this feels less like a harmless change and/or seem somewhat more likely to cause issues).

**Comment by grosser** [comment]
Just make it a major bump ... if someone wants to reuse the old namespace
they can set PlatformAPI = Heroku:: PlatformAPI

**Comment by geemus** [comment]
@grosser you are on top of it. Yeah, if you want to help with a PR, let's get this done. Thanks!
