### ISSUE TITLE
Allow sending commands to add-ons

### ISSUE THREAD

**Issue by lpender** [heroku/platform-api#22]
I'm a bit baffled by the following set of decisions.

1. Deprecate the `heroku` gem.
2. Don't install the "Heroku Toolbelt" by default on Heroku instances.

This forces users to use something like the [Heroku buildpack: Heroku Toolbelt](https://github.com/ddollar/heroku-buildpack-multi) to run `heroku` commands on their staging server.

The `platform-api` provides a partial solution by creating something that can be accessed by a rake task,, but it would be great if it allowed interactions with addons, such as `pgbackups` or `pgextras`.

Thanks!
-Lee

**Comment by abuisman** [comment]
+1 on the `pgbackups`.

What is the recommended way of getting the 'latest backup' url for a certain app?

**Comment by brandur** [comment]
@abuisman Pgbackups does have an API which you can see used from with the code in https://github.com/heroku/heroku, and you should be able to procure a backup URL from it. However, this API is not guaranteed to be stable at the moment, so if you wanted to use it, we'd suggest monitoring for breakage.

**Comment by lpender** [comment]
Hi @brandur!  

Thanks for the response!

I was tasked with writing a script to transfer my Production DB to Staging every day.  

I ended up using the multi-buildpack.

Thanks!

**Comment by dirtyhenry** [comment]
+1 on the pgbackups.

**Comment by geemus** [comment]
closing in favor of #47 (just to reduce duplication a bit)
