### ISSUE TITLE
app.create doesn't work for me

### ISSUE THREAD

**Issue by sckott** [heroku/platform-api#23]
In your README you have `heroku.app.create` after initializing the client with a token. Is this supposed to work?  I installed the lastest from Rubygems...

**Comment by mrosendin** [comment]
Same here, it worked when I passed in an optional name parameter but I need the API to randomly generate a name for me.

**Comment by geemus** [comment]
Yes, I would expect this to work. I'll try to dig in soon.

**Comment by geemus** [comment]
It looks like it works ok for me as long as I pass an empty has as the argument, like `heroku.app.create({})`. I'm not sure when or why that changed, but hopefully that will let you do what you need to do.

**Comment by geemus** [comment]
I believe this is now fixed in the latest release (which allows empty bodies).
