### ISSUE TITLE
Support for Buildpacks?

### ISSUE THREAD

**Issue by devill** [heroku/platform-api#24]
I couldn't figure out how to use the set buildpack functionality of the Heroku API with this gem. Is it supported? If not, where should it be implemented? (I'd be glad to do it, I just don't really find my way around in the code yet.)

**Comment by brandur** [comment]
@devill Hey! You can set a buildpack by setting the "magic" config var `BUILDPACK_URL` to an appropriate value. There's more work underway to bring buildpacks in as a first-class citizen of the API, so this should get better in the not-too-distant future.

**Comment by devill** [comment]
Thank you! I found that option but it is deprecated, so I thought I would ask if the "new" way of doing things was already supported. 

For now I will go with your suggestion, but let me know if I can help in bringing buildpacks in as a first-class citizen of the API.

**Comment by geemus** [comment]
Sorry for the long overdue update, you should now be able to manage this via buildpack installations api, details here: https://devcenter.heroku.com/articles/platform-api-reference#buildpack-installations
