### ISSUE TITLE
Remove heroics dependency

### ISSUE THREAD

**Issue by mikehale** [heroku/platform-api#25]
Shouldn't heroics just be a build/compile time dependency? It would be nice for heroics to be used once to generate code, and then only the generated code is needed. This would reduce runtime dependencies.

/cc @will

**Comment by will** [comment]
Heroics pulls in so much stuff I don't need, netrc, moneta, erubis.

**Comment by geemus** [comment]
Hmm. Not sure how best to test that this didn't break-the-world. I'm somewhat concerned that the generated client actually depends on some of the things, but some initial digging didn't turn up anything super obvious. Any chance one of you would have a place they could do some testing more easily (since unfortunately there don't appear to be tests to speak of here).

**Comment by acorncom** [comment]
@geemus re: your concern about breaking the world, that commit might have ... ;-)  Just set this up in a new app and my app stopped working when I started using the referenced commit:

```sh
vagrant@localhost:/rails-app$ rails g model my-model
/rails-app/vendor/bundle/ruby/2.3.0/bundler/gems/platform-api-602d4206ca14/lib/platform-api.rb:1:in `require': cannot load such file -- heroics (LoadError)
	from /rails-app/vendor/bundle/ruby/2.3.0/bundler/gems/platform-api-602d4206ca14/lib/platform-api.rb:1:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
	from /rails-app/config/application.rb:17:in `<top (required)>'
	from /rails-app/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `require'
	from /rails-app/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:82:in `preload'
	from /rails-app/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:143:in `serve'
	from /rails-app/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /rails-app/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /rails-app/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /rails-app/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

As soon as I shifted back to the latest published gem `0.8` things immediately started working ...

**Comment by geemus** [comment]
Thanks for the heads up, will dig in.

**Comment by geemus** [comment]
It's used directly, kind of a lot. So just dropping seems not super tenable I fear. Slimming down what heroics uses at test/development and what it generally depends on seems like it might be the better way to go.

**Comment by mikehale** [comment]
Maybe a version bump could allow us to introduce this breaking change?

**Comment by geemus** [comment]
We would still have to change a lot I think. Right now the generated client does a number of `Heroics.whatever` type calls, which we would need to pull into the main thing.

**Comment by mikehale** [comment]
Gotcha, so probably not worth it until we are at the point where we can generate a static client with 0 runtime heroics dependencies.

**Comment by geemus** [comment]
Yeah. I didn't realize how intertwined it was there.
