### ISSUE TITLE
Errno::EACCES: Permission denied @ dir_s_mkdir - /home/webapp

### ISSUE THREAD

**Issue by strika** [heroku/platform-api#39]
I have an application that's using Platform API deployed to AWS EC2. Problem is that I see this exception `Errno::EACCES: Permission denied @ dir_s_mkdir - /home/webapp` when I try to instantiate Platform API client. The relevant exception happens on [this line of code](https://github.com/heroku/platform-api/blob/v0.5.0/lib/platform-api/client.rb#L77).

I actually think that there are 2 problems here:

1. Platform API choice of a file cache in the home directory doesn't work in all scenarios.
2. Although Platform API client allows overriding the cache with an option (`PlatformAPI.connect('my-api-key', cache: Moneta.new(:Memory))`) the client is written in such a way that it tries to create the file store in the home directory, although it's not going to be used - https://github.com/heroku/platform-api/blob/v0.5.0/lib/platform-api/client.rb#L64. This is actually a problem in Heroics.

I'm not sure what the optimal solution is but I would like to ask you to consider changing one or both of those things. Let me know if you need any further information on this. Thanks!

**Comment by geemus** [comment]
Thanks for the heads up and detailed report. It seems like the easiest thing to improve here would be 2. ie if you override we should avoid trying to do something with the file that you would no longer need/use. Sounds like that might be in heroics directly though? Would you be up for helping with a PR there? Thanks!

**Comment by strika** [comment]
I agree that option 2 sounds better. Thanks.

Let me know how I can help.

**Comment by geemus** [comment]
I think https://github.com/interagent/heroics/pull/72 should do it?

**Comment by strika** [comment]
Yes, that looks good! I'd be happy to test it once `platform-api` is regenerated with the new version of Heroics.

**Comment by geemus** [comment]
Alright, I think it should be fixed on master. Could you confirm? If everything looks good I can try to follow up with a release shortly. Thanks!

**Comment by strika** [comment]
Unfortunately, this doesn't fix the problem, but this should do it https://github.com/interagent/heroics/pull/73.

**Comment by geemus** [comment]
Should be bumped/updated again, care to take another peak?

**Comment by strika** [comment]
@geemus This time it works well. Thanks!

**Comment by geemus** [comment]
Released as 0.6.0. Thanks!

**Comment by strika** [comment]
Thank you!
