### ISSUE TITLE
How would I create an app in a particular space?

### ISSUE THREAD

**Issue by Reifier** [heroku/platform-api#51]
We are migrating to spaces, and this gem would probably be useful. However, I can't find how to use a space attribute for an app in this gem. 

https://devcenter.heroku.com/articles/platform-api-reference#app

Is that currently possible?

**Comment by geemus** [comment]
I think you'll want to reference the organization app, instead of just plain vanilla apps, see: https://devcenter.heroku.com/articles/platform-api-reference#organization-app-create
