### ISSUE TITLE
Is there a way to stop a Dyno?

### ISSUE THREAD

**Issue by AaronMegaphone** [heroku/platform-api#52]
I can't seem to find a way to stop a Dyno using the platform-api gem. Is this by design? I can see here https://devcenter.heroku.com/articles/platform-api-reference that the API includes a Dyno Stop endpoint. The only alternative I can think of is to create a Dyno with Dyno#create and run `heroku ps:stop run.1`

**Comment by geemus** [comment]
It's not particularly clear as currently documented, but restart will also give you what you need (delete dyno). Basically, when you call this you get one of two things. 1) it's a permanent dyno from your procfile, so it gets replaced with a new dyno or 2) it's a run/scheduler dyno, so it just gets stopped. Hope that gets you what you need.

**Comment by AaronMegaphone** [comment]
@geemus Thanks a lot that is exactly what I'm looking for. A kill switch to stop a one-off dyno.

**Comment by AaronCowan** [comment]
Hey @geemus I'm using `platform-api (0.2.0)`

Starting a one-off dyno with this command 

`heroku.dyno.create(heroku_app, {command: "while :; do echo 'hit ctrl-c'; sleep 1; done", type: "test"})`

Heroku logs this:

`app[api]: Starting process with command 'while :; do echo 'hit ctrl-c'; sleep 1; done' by user`


But this dyno is not killed with the command

`heroku.dyno.restart(heroku_app, "test.1234") # assuming the Dyno name is test.1234 `
Returned is an empty hash `{}`
