### ISSUE TITLE
Unable to create custom DNS + CNAME

### ISSUE THREAD

**Issue by kuldeepaggarwal** [heroku/platform-api#55]
I am trying to create a custom DNS + CNAMe via `platform-api` gem but still not able to set custom CNAME, e.g.

```rb
heroku = PlatformAPI.connect_oauth('API-key')
heroku.domain.create( 'brandnew-advertiser-fe-staging', {"hostname" => 'mediacom.brandnew.in', "kind" => "custom", "cname" => "brandnew-advertiser-fe-staging.herokuapp.com"})

# => {"app"=>{"id"=>"<APP_ID>", "name"=>"brandnew-advertiser-fe-staging"}, "cname"=>"mediacom.brandnew.in.herokudns.com", "created_at"=>"2017-01-13T10:02:40Z", "hostname"=>"mediacom.brandnew.in", "id"=>"<ID>", "kind"=>"custom", "status"=>"pending", "updated_at"=>"2017-01-13T10:02:40Z"}
```

you can see that cname is not same.

**Comment by ransombriggs** [comment]
@kuldeepaggarwal `cname` is a readonly attribute that is set internally by heroku.  Sorry that this is not obvious from the platform docs.  What you should do is omit `cname` from the post body when you are generating a custom domain and let heroku generate a `cname` for you.

When you created your custom domain heroku set up `mediacom.brandnew.in.herokudns.com` for you to point your DNS CNAME record at.  Once DNS is configured properly, this will allow `mediacom.brandnew.in` to be served by heroku infrastructure.

**Comment by geemus** [comment]
This appear to have a clear answer now, closing. Please let us know if you have further questions.

**Comment by ayushgangrade11** [comment]
Hey Ransombriggs & geemus , I am also stuck on a similar problem where my python app hosted on heroku has a default heroku dns address and I am saving the same entry in NS and keeping CNAME as empty. I am unable to make requests to my domain.

**Comment by geemus** [comment]
@ayushgangrade11 sorry to hear you are still having issues. If you could file a support ticket on heroku, they should better be able to help you with that specific setup.
