### ISSUE TITLE
Add hooks so Let's Encrypt can be directly supported

### ISSUE THREAD

**Issue by david-a-wheeler** [heroku/platform-api#63]
[Heroku's automated HTTPS certificate management](https://blog.heroku.com/announcing-automated-certificate-management) was recently announced, based on [the widely-used Let's Encrypt service](https://letsencrypt.org/2017/01/06/le-2016-in-review.html).  However, Heroku's mechanism *cannot* be used with CDNs (like Fastly or CloudFlare), which makes the new service useless for a lot of people.  [Gem letsencrypt-rails-heroku](https://github.com/pixielabs/letsencrypt-rails-heroku) enables people to use Let's Encrypt even with a CDN.

However, this gem requires a *modified* version of platform-api, here: https://github.com/jalada/platform-api

Can heroku/platform-api be modified so that it includes the hooks needed to support the [gem letsencrypt-rails-heroku](https://github.com/pixielabs/letsencrypt-rails-heroku) ?

Thanks!

**Comment by david-a-wheeler** [comment]
I now realize this may overlap some existing issues and PRs, e.g., [issue 49](https://github.com/heroku/platform-api/issues/49) and [pull request 56](https://github.com/heroku/platform-api/pull/56).

**Comment by geemus** [comment]
@david-a-wheeler thanks for details, closing in favor of those other issues (to avoid repeating conversations). Thanks for linking them together, will try to get a better idea of timeline for you soon.
