### ISSUE TITLE
BadRequest - 400 BadRequest Missing Host Header on nearly all functions

### ISSUE THREAD

**Issue by ejlax** [heroku/platform-api#65]
I am using the client.connect_oauth(<oauth_token>) to generate my client but when trying to use the client to return `client.config_var.info_for_app(app_name)` (among other calls) Excon returns `Excon::Error::BadRequest` =>
`'400 Bad Request: missing required Host header' (JSON::ParserError)`

I am currently using version 1.0.1 and my oauth_token is generated via the CLI `heroku authorizations:create --short`

**Comment by ejlax** [comment]
The issue was actually with the oauth_token being passed into the client creation. there was a "\n" trailing the token which was prematurely ending the headers causing the requests to fail

**Comment by geemus** [comment]
Ah, got it. Thanks for the update and glad you were able to get that sorted out.
