### ISSUE TITLE
Excon warning: Invalid Excon connection keys: :thread_safe_sockets

### ISSUE THREAD

**Issue by arielkirkwood** [heroku/platform-api#82]
Hi, I'm trying to use this gem in a Rake task to create or delete Heroku domains, and I'm running into this error. I wasn't able to find any issues on the Excon repo detailing how this could happen, so I'm starting by opening an issue here.

Thanks in advance for your help!

**Comment by brandur** [comment]
@arielkirkwood I don't think that this gem is very well maintained anymore. In your case the first thing I'd checked is that you're on a reasonably recent version of Excon. It looks like this option was probably added in 0.42.0:

https://github.com/excon/excon/blob/aec477227d1b45c097c17a809acb8a50e4785326/changelog.txt#L225

**Comment by arielkirkwood** [comment]
@brandur Thanks for the quick response!
