### ISSUE TITLE
Review App beta

### ISSUE THREAD

**Issue by estiens** [heroku/platform-api#95]
Will this gem support the new review app API (either in beta or when they come out of beta?)

**Comment by cguess** [comment]
I too could really use this. I'm using straight http requests in the meantime, but putting the review apps in here would be very useful.

**Comment by meenie** [comment]
Any update on this? I didn't realize that this Ruby Gem didn't support the review app API before I upgraded our pipeline to use it. So now I'm a bit stuck.

**Comment by michaelirey** [comment]
Any update here?

**Comment by Porkechebure** [comment]
> Any update here?
YEAHHOOOOOOOOOOOOO HOLY MOLY YEAHHHHHHHH YOHOHOHOHOOOOOOOO

**Comment by estiens** [comment]
2.5 years later do we have this?

**Comment by estiens** [comment]
Oh, we do indeed! I suppose I can close this, but even a slight bit of documentation beyond the api itself would be great...
